### ISSUE TITLE
Colour artifacts encoding low resolution content.

### ISSUE THREAD

**Issue by jossgray** [Vidvox/hap#11]
Encoding low res video results. Source is a 16x16 png. I'm guessing this is a limitation of the DXT compressor.

Source

![test_16x16](https://cloud.githubusercontent.com/assets/674182/10547884/e314748e-73eb-11e5-859c-fa45355861a2.png)

After HAP encoding, full quality

![test_16x16_post](https://cloud.githubusercontent.com/assets/674182/10547888/e7394f8a-73eb-11e5-893b-3f1008847323.png)

**Comment by bangnoise** [comment]
Presumably this is with the QT codec - opened an issue there.
