### ISSUE TITLE
Transfer Ownership of Repo

### ISSUE THREAD

**Issue by DomAmato** [Vidvox/hap#19]
Not really a code issue but as it currently stands it seems my hap-directshow repo is the top one transferred from RenderHeads google code archive. I was wondering if you would be interested in taking over ownership since I don't have time to really keep up with it now that I have started my PhD program. I feel guilty not being able to answer questions or addressing issues in a timely manner so I figured it would be best to transfer it.

**Comment by bangnoise** [comment]
Thanks - and thanks for the support job you've done thus far - I've reached out to RenderHeads in case they have any strong feelings.

**Comment by DomAmato** [comment]
Any word from RenderHeads? I will start the transfer since I am pretty sure you will need to approve of it

**Comment by bangnoise** [comment]
No reply from RenderHeads.

You will have to make the transfer as the owner. Navigate to the project page, hit Settings (right-most tab), and scroll down to the Transfer section in the red danger zone. Vidvox will then have to confirm the transfer.

**Comment by DomAmato** [comment]
The problem is I can't transfer it to VidVox, can I transfer it to you instead?
![capture](https://cloud.githubusercontent.com/assets/6936055/21703001/a9c3004e-d374-11e6-8eec-fb89d90e14a4.PNG)

**Comment by bangnoise** [comment]
Strange - okay

**Comment by bangnoise** [comment]
Now at https://github.com/Vidvox/hap-directshow

Thanks @DomAmato
