### ISSUE TITLE
Decoding not happening on Graphic Card

### ISSUE THREAD

**Issue by maimframe** [Vidvox/hap#24]
Hi, new to Github, registered for this issue, hope I am doing this correctly :)

So, I have an issue where Hap videos seems to be decoded with the GPU in my CPU rather than with my AMD Firepro W9100.

I drew this conclusions because monitoring the GPU with GPU-Z I noticed the amount of memory reserved on my AMD card was 304MB which correspond to the 249MB required for HD output and then some. The more outputs I used on the card the higher the amount of reserved memory on my GPU went up. However no amount of concurent HAP files being played changed that amount. Also I tested two system one with an 8GB card and the other with a 16GB card, both  resulted in graphic memory error at the exact same amount of concurent Hap files.

The host software is Watchout 6 (6.1.5) by Dataton. So I don't know if the issue is with Watchout not dispatching the decoding on the good hardware of if it is a problem with the Hap decoder itself, hence me posting the issue here.

I use i7 6900 on X99 with 16GB of DDR4 ram 2400, the video card is AMD W9100 for the 16GB card and 480 Fury for the 8GB card, the 8GB card is in a system with an i76800. Everything else is the same. The OS is win7pro.

Hope I did this right :)
regards

**Comment by bangnoise** [comment]
This is an issue with your playback software. Contact Dataton.
