### ISSUE TITLE
[Formats] BC6 integration

### ISSUE THREAD

**Issue by mrvux** [Vidvox/hap#25]
Hello, just another one, but since nowadays BC6 tends to offer a pretty decent quality, with reasonably fast encoders as well, it could totally be worth adding (In Unsigned/Signed version)

For unsigned version we can simply use... 6 ;)
(so 0xA6, 0xB6, 0xC6 )

For signed version, we can use 9 I suppose.
(so 0xA9, 0xB9, 0xC9 )

**Comment by bangnoise** [comment]
Yeah this is something we're thinking about

**Comment by bangnoise** [comment]
#42
