### ISSUE TITLE
conversion to hap with FFmpeg

### ISSUE THREAD

**Issue by mpedge** [Vidvox/hap#32]
Hi,

I am having problems playing back DirectShow hap files (.avi) in either Cinder or openFrameworks DirectShow blocks/addons.

I've asked the developers of openFrameworks addon and [they are having the same issue](https://github.com/secondstory/ofxDSHapVideoPlayer/issues/13).

Would you perhaps have any suggestion on how to approach this problem?

Thanks!
MP

**Comment by bangnoise** [comment]
This is a problem with their implementation. I've left a comment on the linked issue for the OF addon, feel free to duplicate it to the Cinder block if you think it might apply there too.
