### ISSUE TITLE
Dead link to Snappy Format Description in the external references in the specification

### ISSUE THREAD

**Issue by tomokikun** [Vidvox/hap#35]
As described in the title, I found a dead link to Snappy Format Description in the external references in the specification.
https://github.com/Vidvox/hap/blob/master/documentation/HapVideoDRAFT.md#external-references

I encountered "404 not found" when I accessed to http://snappy.googlecode.com/svn/trunk/format_description.txt

**Comment by bangnoise** [comment]
Thanks for the heads-up - fixed now.
