### ISSUE TITLE
How to make sure is Hap decode on GPU or CPU?

### ISSUE THREAD

**Issue by wwfly93** [Vidvox/hap#39]
Hi,
In my opinion, when using a computer's graphics hardware to decode, open the "Task manager" -> "Performance" -> "GPU" dialog box, we can find the "Video Decode"  usage rate is not-zero. but when i play the media with the VLC software, the usage rate always zero.  video file is downlode from  "Test Materials" ("https://github.com/Vidvox/hap").

Test environment：
OS: Windwos 10 20H2
GPU: Nvidia GTX 1650
CPU: Intel(R) Core(TM) i7-9750H
SoftWare: VLC 3.0.14
video file: Test Materials -> Hap_Test_FFmpeg->Hap_ffmpeg_64.mov

**Comment by bangnoise** [comment]
Hap is a video format, and it is up to the decoding software whether it uses the CPU or GPU. VLC gets its Hap support from FFmpeg, so support for GPU decoding of Hap would have to be added in those projects.

**Comment by wwfly93** [comment]
> Hap is a video format, and it is up to the decoding software whether it uses the CPU or GPU to decode it. VLC gets its Hap support from FFmpeg, so support for GPU decoding of Hap would have to be added in those projects.

thanks for you replay.

I still have some question. I want to use VLC to play some Hap media which were encoded with ffmpeg command line. but the playback effect is not smooth enough.  Combine with your response. can i be sure that ffmpeg is not support GPU decode for HAP format.

I also downlowd “ofxHapPlayer” and replace the “sampleHap.mov”  with my own file, it isn't smooth enough too.  did it support GPU decode? or can you give me any suggestions？
