### ISSUE TITLE
Website link to ffmpeg on windows does not work

### ISSUE THREAD

**Issue by sunep** [Vidvox/hap#41]
Hi

I am not sure that this is the correct place to post this, but here goes.

If you go to [Using HAP](https://hap.video/using-hap.html), the link to download ffmpeg for windows does not work.
An updated link to a project that does work would be a good idea along with instructions on which version to download (shared works for me)
As far as I can tell, there are two projects for windows, where https://github.com/BtbN/FFmpeg-Builds/releases looks good (it's on github).

Please point me in the right direction in case I am posting this in the wrong place.

Sune

**Comment by bangnoise** [comment]
See Vidvox/hapvideosite#27
