### ISSUE TITLE
Mac Silicon OSX 13, seems to not work

### ISSUE THREAD

**Issue by ryderr** [Vidvox/hap#46]
cant get HAP to install on latest MAC

**Comment by bangnoise** [comment]
Please don't cross-post issues. This project is for the Hap format and not for any user-installable products.

**Comment by bentoncbainbridge** [comment]
Tom, where should we post Hap CODEC installation issues? thanks, Benton

**Comment by bangnoise** [comment]
There are many Hap encoders and decoders, mostly commercial, some open-source. Which one are you having issues with?

**Comment by bentoncbainbridge** [comment]
Tom, I'm trying to install the version that comes with VDMX - thus I thought Vidvox/hap/issues was the right thread?

macOS 12.5.1
MacBook Pro (14-inch, 2021)
Apple M1 Max
VDMX version b0.8.8.0.0

**Comment by bentoncbainbridge** [comment]
Thanks Tom, thanks Dave - I just installed VDMX Version b0.8.8.0.5 and the AVF Batch Converter and Hap is working fine now!
