### ISSUE TITLE
What does HAP stand for?

### ISSUE THREAD

**Issue by lachlansleight** [Vidvox/hap#48]
Sorry if this is an insane issue but I just spent like 15 minutes researching and I can't find this anywhere.

I'm so curious!

**Comment by dlublin** [comment]
Hardware Accelerated Playback

**Comment by JonnyTech** [comment]
> Hardware Accelerated Playback

Do you have a reference for that?

**Comment by dlublin** [comment]
No reference but I was there when we came up with the name.
