### ISSUE TITLE
How to install codec on Windows?

### ISSUE THREAD

**Issue by moebiussurfing** [Vidvox/hap#49]
The official website (https://hap.video/using-hap) links to a non existing website.
http://[ffmpeg.zeranoe.com](http://ffmpeg.zeranoe.com/builds/)/builds/

**Comment by moebiussurfing** [comment]
should I compile by myself? any tip around is welcome.

**Comment by bangnoise** [comment]
https://ffmpeg.org/download.html and choose a build which includes the snappy library
