### ISSUE TITLE
ffmpeg resolution or bitrate error

### ISSUE THREAD

**Issue by flat4er** [Vidvox/hap#52]
`[hap @ 0x5ff178265380] Video size 8000x626 is not multiple of 4.
[vost#0:0/hap @ 0x5ff178264fc0] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
Error while filtering: Invalid data found when processing input
[out#0/mov @ 0x5ff178263740] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=N/A bitrate=N/A speed=N/A    
Conversion failed!
`

**Comment by bangnoise** [comment]
This is an ffmpeg limitation, please report it there. Thanks!
